### ISSUE TITLE
Run the Program

### ISSUE THREAD

**Issue by mehrdad78** [Lartu/coraldb#1]
Hi there! There is a paper has same title of the repo, your code is the implementation of that paper?
"CoralDB: A Collaborative Database for Data Sharing based on Permissioned Blockchain"

**Comment by mehrdad78** [comment]
> Hi there! There is a paper has same title of the repo, your code is the implementation of that paper?
**"CoralDB: A Collaborative Database for Data Sharing based on Permissioned Blockchain"**

**Comment by Lartu** [comment]
Hi there! No, not at all, I wasn't aware of that paper!
